import { Router, Request, Response } from "express";
import { authMiddleware } from "../middlewares/auth.middleware";
import providers_routes from "./providers.routes";
import agencies_routes from "./agencies.routes";
import services_routes from "./services.routes";
import forwarders_routes from "./forwarders.routes";
import carriersRoutes from "./carriers.routes";
import customers_routes from "./customers.routes";
import provinces_routes from "./provinces.routes";
import receivers_routes from "./receivers.routes";
import users_routes from "./users.routes";
import customs_rates_routes from "./customs.rates.routes";
import roles_routes from "./roles.routes";
import analytics_routes from "./analytics.routes";
import partners_routes from "./partners.routes";
import orders_routes from "./orders.routes";
import products_routes from "./products.routes";
import shippingRatesRoutes from "./shipping.rates.routes";
import trackingRoutes from "./tracking.routes";
import dispatchRoutes from "./dispatch.routes";
import electricRoutes from "./electric.routes";
import configRoutes from "./logs.config.routes";
import logsRoutes from "./logs.routes";
import issuesRoutes from "./issues.routes";
import parcelsRoutes from "./parcels.routes";
import legacyRoutes from "./legacy.routes";
import legacyIssuesRoutes from "./legacy-issues.routes";
import interAgencyDebtsRoutes from "./inter-agency-debts.routes";
import containersRoutes from "./containers.routes";
import flightsRoutes from "./flights.routes";
import palletsRoutes from "./pallets.routes";
import warehousesRoutes from "./warehouses.routes";
import manifestVerificationRoutes from "./manifest-verification.routes";
import deliveryRoutesRoutes from "./delivery-routes.routes";
import financialReportsRoutes from "./financial-reports.routes";

const router = Router();

router.get("/", (req: Request, res: Response) => {
   res.status(200).json({ status: "ok", message: "Welcome to CTEnvios API V1", timestamp: new Date().toISOString() });
});

router.use("/providers", authMiddleware, providers_routes);
router.use("/forwarders", authMiddleware, forwarders_routes);
router.use("/agencies", authMiddleware, agencies_routes);
router.use("/carriers", authMiddleware, carriersRoutes);
router.use("/services", authMiddleware, services_routes);
router.use("/customs-rates", authMiddleware, customs_rates_routes);
router.use("/users", users_routes);
router.use("/customers", authMiddleware, customers_routes);
router.use("/receivers", authMiddleware, receivers_routes);
router.use("/provinces", authMiddleware, provinces_routes);
router.use("/roles", authMiddleware, roles_routes);
router.use("/analytics", authMiddleware, analytics_routes);
router.use("/partners", partners_routes);
router.use("/orders", orders_routes);
router.use("/products", authMiddleware, products_routes);
router.use("/shipping-rates", authMiddleware, shippingRatesRoutes);
router.use("/dispatches", authMiddleware, dispatchRoutes);
router.use("/tracking", trackingRoutes);
router.use("/electric", authMiddleware, electricRoutes);
router.use("/config", configRoutes);
router.use("/logs", logsRoutes);
router.use("/issues", authMiddleware, issuesRoutes);
router.use("/parcels", authMiddleware, parcelsRoutes);
router.use("/legacy", legacyRoutes);
router.use("/legacy-issues", authMiddleware, legacyIssuesRoutes);
router.use("/inter-agency-debts", interAgencyDebtsRoutes);
router.use("/containers", authMiddleware, containersRoutes);
router.use("/flights", authMiddleware, flightsRoutes);
router.use("/pallets", authMiddleware, palletsRoutes);
router.use("/warehouses", authMiddleware, warehousesRoutes);
router.use("/manifest-verifications", authMiddleware, manifestVerificationRoutes);
router.use("/delivery-routes", authMiddleware, deliveryRoutesRoutes);
router.use("/financial-reports", financialReportsRoutes);

export default router;
