import { FeeType, CityType } from "@prisma/client";
export const customsRates = [
   {
      name: `Alimentos/Aseo`,
      description: `Alimentos/Aseo`,
      chapter: `Miscelaneas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 0,
      custom_value: 10.0,
      max_quantity: 10,
   },
   {
      name: `Planchas electricas domesticas`,
      description: `Plancha electrica domestica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Refrigeradores domesticos`,
      description: `Refrigerador domestico`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 694,
      custom_value: 300.0,
      max_quantity: 2,
   },
   {
      name: `Congeladores o freezer domesticos.`,
      description: `Congelador o freezer domesticos.`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 823,
      custom_value: 350.0,
      max_quantity: 2,
   },
   {
      name: `Dispensadores de agua`,
      description: `Dispensador de agua`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Minibar.`,
      description: `Minibar.`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Cocina y hornos de gas`,
      description: `Cocina y horno de ga`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Cocina y hornillas electricas por induccion`,
      description: `Cocina y hornilla electrica por induccion`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Cocinas y hornillas electricas sin horno`,
      description: `Cocina y hornilla electrica sin horno`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Cocinas y hornillas electricas sin horno`,
      description: `Cocina y hornilla electrica sin horno`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2109,
      custom_value: 850.0,
      max_quantity: 2,
   },
   {
      name: `Extractor de grasa y campana`,
      description: `Extractor de grasa y campana`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Horno microonda`,
      description: `Horno microonda`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Hornos electricos para uso domestico`,
      description: `Horno electrico para uso domestico`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Parrillada o grill`,
      description: `Parrillada o grill`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Sartenes electricos y similares`,
      description: `Sarten electrico y similar`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Olla arrocera electrica`,
      description: `Olla arrocera electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Olla vaporera electrica`,
      description: `Olla vaporera electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Olla multifuncion electrica`,
      description: `Olla multifuncion electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Olla asadora de conveccion halogena`,
      description: `Olla asadora de conveccion halogena`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Freidora electrica`,
      description: `Freidora electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Sandwichera electrica`,
      description: `Sandwichera electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Tostadora electrica de pan`,
      description: `Tostadora electrica de pan`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Maquinas lavadoras/ secadoras domesticas`,
      description: `Maquina lavadoras/ secadora domestica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Lava vajilla domestico`,
      description: `Lava vajilla domestico`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Maquina de coser, tejer y bordar`,
      description: `Maquina de coser, tejer y bordar`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Secador o rizador / plancha de pelo`,
      description: `Secador o rizador / plancha de pelo`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Secador de cabellos`,
      description: `Secador de cabellos`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Maquina de pelar electrica`,
      description: `Maquina de pelar electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Aspiradora`,
      description: `Aspiradora`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Ducha electrica`,
      description: `Ducha electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Calentador de agua Electrico`,
      description: `Calentador de agua Electrico`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 103,
      custom_value: 70.0,
      max_quantity: 2,
   },
   {
      name: ` Calentador de Agua Gas`,
      description: ` Calentador de Agua Ga`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Cafetera electrica`,
      description: `Cafetera electrica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Batidora`,
      description: `Batidora`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Licuadora`,
      description: `Licuadora`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Procesador de alimentos`,
      description: `Procesador de alimento`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Picador de especies y vegetales`,
      description: `Picador de especie y vegetal`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Mezcladoras`,
      description: `Mezcladora`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Molinos`,
      description: `Molino`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Televisores convencionales`,
      description: `Televisor convencional`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Televisores hasta 32 pulgadas`,
      description: `Televisor pantalla plana hasta 32 pulgada`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 566,
      custom_value: 250.0,
      max_quantity: 2,
   },
   {
      name: `Televisores de 32 pulgadas hasta 42 pulgadas`,
      description: `Televisor mayor de 32 pulgada hasta 42 pulgada`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
      max_quantity: 2,
   },
   {
      name: `Televisores mayores de 42 pulgadas`,
      description: `Televisor mayor de 42 pulgada`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 1209,
      custom_value: 500.0,
      max_quantity: 2,
   },
   {
      name: `Caja decodificadora digital TV`,
      description: `Caja decodificadora digital TV`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Equipos de musica`,
      description: `Equipo de musica`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Equipo de musica portatil`,
      description: `Equipo de musica portatil`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Teatro en casa o similares`,
      description: `Teatro en casa o similar`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 231,
      custom_value: 120.0,
      max_quantity: 2,
   },
   {
      name: `Mezclador de sonido`,
      description: `Mezclador de sonido`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
      max_quantity: 2,
   },
   {
      name: `Reproductor de video`,
      description: `Reproductor de video`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 200,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Consolas de video juegos`,
      description: `Consola de video juego`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Ventiladores`,
      description: `Ventilador`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Aire Acondicionado/Split (hasta 9000 BTU)`,
      description: `Aire Acondicionado/Split (hasta 9000 BTU)`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Aire Acondicionado/Split (mayor de 9000 hasta 12000 BTU)`,
      description: `Aire Acondicionado/Split (mayor de 9000 hasta 12000 BTU)`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Aire Acondicionado/Split (mayor de 12000 BTU hasta 24000 BTU)`,
      description: `Aire Acondicionado/Split (mayor de 12000 BTU hasta 24000 BTU)`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 1851,
      custom_value: 750.0,
      max_quantity: 2,
   },
   {
      name: `Generadores Electricos hasta 900 va`,
      description: `Generador Electrico hasta 900va`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Generadores Electricos Mayores de 900va hasta 1500va`,
      description: `Generador Electrico de 900 va hasta 1500 va`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 1209,
      custom_value: 500.0,
      max_quantity: 2,
   },
   {
      name: `Generadores Electricos Mayores de 1500 va hasta 15Kva`,
      description: `Generador Electrico de 1500 va hasta 15Kva`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2366,
      custom_value: 950.0,
      max_quantity: 2,
   },
   {
      name: `Casco o armazon de refrigeradores, freezer y aires acondicionados con todos los componentes excepto el compresor`,
      description: `Casco o armazon de refrigeradores, freezer y air acondicionado con todo lo component excepto el compresor`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 566,
      custom_value: 250.0,
      max_quantity: 2,
   },
   {
      name: `Otros tipos de motores de equipos electrodomesticos`,
      description: `Otro tipo de motor de equipo electrodomestico`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Compresores de equipos de clima y refrigeracion`,
      description: `Compresor de equipo de clima y refrigeracion`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Bombas de agua o compresores para agua`,
      description: `Bomba de agua o compresor para agua`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Partes, piezas y accesorios de compresores y bombas para agua`,
      description: `Partes, pieza y accesorio de compresor y bomba para agua`,
      chapter: `Electrodomesticos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Microcomputadora de Mesa Mesa`,
      description: `Microcomputadora de Mesa Mesa`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Microcomputadora portatil (laptop).`,
      description: `Microcomputadora portatil (laptop).`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 566,
      custom_value: 250.0,
      max_quantity: 2,
   },
   {
      name: `Table PC, dispositivos para la lectura digital y productos similares`,
      description: ` Table PC, dispositivo para la lectura digital y producto similar`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Mini laptop`,
      description: ` Mini laptop`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
   },
   {
      name: `Dispositivos de almacenamiento, memorias y similares`,
      description: `Dispositivo de almacenamiento, memoria y similar`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Torre de computadora`,
      description: `Torre de computadora`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 103,
      custom_value: 70.0,
      max_quantity: 2,
   },
   {
      name: `Disco duro incluyendo el HDD player`,
      description: `Disco duro incluyendo el HDD player.`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Monitor de computadora`,
      description: `Monitor de computadora`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Backup (UPS)`,
      description: `Backup (UPS)`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Impresoras. Fotocopiadoras`,
      description: `Impresoras. Fotocopiadora`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Scanners`,
      description: `Scanner`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Telefonos convencionales alambricos`,
      description: `Telefono convencional alambrico`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Telefonos inalambricos`,
      description: `Telefono inalambrico`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Telefonos celulares o inteligentes`,
      description: `Telefono celular o inteligent`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Intercomunicadores domesticos`,
      description: `Intercomunicador domestico`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Fax alambrico`,
      description: `Fax alambrico`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Equipos de fax inalambricos`,
      description: `Equipo de fax inalambrico`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Microfonos inalambricos y sus accesorios`,
      description: `Microfono inalambrico y su accesorio`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Microfonos alambricos y sus accesorios`,
      description: `Microfono alambrico y su accesorio`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Dispositivos para redes de datos (routers, switches y similares).`,
      description: `Dispositivo para red de dato (routers, switch y similares).`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Transmisores y transceptores de radio de cualquier naturaleza y servicios, estaciones fijas, moviles y personales (walkietalkie y telefonos satelitales), sus dispositivos y amplificadores de potencia`,
      description: `Transmisor y transceptor de radio de cualquier naturaleza y servicios, estacion fijas, movil y personal (walkietalkie y telefono satelitales), su dispositivo y amplificador de potencia`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Geolocalizador`,
      description: `Geolocalizador`,
      chapter: `Equipos de Computo o Similares`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Instrumentos de cuerda`,
      description: `Instrumento de cuerda`,
      chapter: `Instrumentos Musicales`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Instrumentos de teclado`,
      description: `Instrumento de teclado`,
      chapter: `Instrumentos Musicales`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Instrumentos de viento`,
      description: `Instrumento de viento`,
      chapter: `Instrumentos Musicales`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Instrumentos de percusion`,
      description: `Instrumento de percusion`,
      chapter: `Instrumentos Musicales`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Los demas instrumentos musicales`,
      description: `Lo demas instrumento musical`,
      chapter: `Instrumentos Musicales`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 694,
      custom_value: 300.0,
      max_quantity: 2,
   },
   {
      name: `Juego de sala`,
      description: `Juego de sala`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Juego de cuarto`,
      description: `Juego de cuarto`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Juego de comedor`,
      description: `Juego de comedor`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 231,
      custom_value: 120.0,
      max_quantity: 2,
   },
   {
      name: `Juego de mueble de cocinas compuesta por modulos sin electrodomesticos incluidos`,
      description: `Juego de mueble de cocina compuesta por modulo sin electrodomestico incluido`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
      max_quantity: 2,
   },
   {
      name: `Piezas de muebles (silla, mesa, butaca, sillones y similares)`,
      description: `Pieza de muebl (silla, mesa, butaca, sillon y similares)`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Sillas giratorias`,
      description: `Silla giratoria`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Buros.`,
      description: `Buros.`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Mesa para computadoras`,
      description: `Mesa para computadora`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Libreros`,
      description: `Librero`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Estantes`,
      description: `Estant`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 103,
      custom_value: 70.0,
      max_quantity: 2,
   },
   {
      name: `Comodas y gaveteros`,
      description: `Comoda y gavetero`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Repisas`,
      description: `Repisa`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Colchones`,
      description: `Colchon`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Los demas muebles`,
      description: `Lo demas muebl`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Muebles para uso del bebe (cuna, coches, corrales, mecedoras, andadores y similares)`,
      description: `Muebl para uso del bebe (cuna, coches, corrales, mecedoras, andador y similares)`,
      chapter: `Mobiliario`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Ciclomotores electricos de hasta dos plazas`,
      description: `Ciclomotor electrico de hasta do plaza`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Baterias o acumuladores de litio`,
      description: `Bateria o acumulador de litio`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Otras baterias y acumuladores`,
      description: `Otra bateria y acumulador`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 35.0,
      max_quantity: 2,
   },
   {
      name: `Kit o set de baterias de Gel`,
      description: `Kit o set de bateria de Gel`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Carburador`,
      description: `Carburador`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Delco (distribuidor)`,
      description: `Delco (distribuidor)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Guardafangos`,
      description: `Guardafango`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Parabrisas`,
      description: `Parabrisa`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Neumaticos para autos ligeros (con o sin camaras)`,
      description: `Neumatico para auto ligero (con o sin camaras)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Neumaticos para autos pesados (con o sin camaras)`,
      description: `Neumatico para auto pesado (con o sin camaras)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Neumaticos para motos o ciclomotores (con o sin camaras)`,
      description: `Neumatico para moto o ciclomotor (con o sin camaras)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 35.0,
      max_quantity: 2,
   },
   {
      name: `Camaras para neumaticos de autos ligeros`,
      description: `Camara para neumatico de auto ligero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Camaras para neumaticos de autos pesados`,
      description: `Camara para neumatico de auto pesado`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Camaras para neumaticos de motos o ciclomotores`,
      description: `Camara para neumatico de moto o ciclomotor`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
      max_quantity: 2,
   },
   {
      name: `Llantas para autos ligeros`,
      description: `Llanta para auto ligero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Llantas para autos pesados`,
      description: `Llanta para auto pesado`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Llantas para motos o ciclomotores`,
      description: `Llanta para moto o ciclomotor`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 35.0,
      max_quantity: 2,
   },
   {
      name: `Amortiguadores`,
      description: `Amortiguador`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Bobina de encendido`,
      description: `Bobina de encendido`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
      max_quantity: 2,
   },
   {
      name: `Cajas de Velocidad`,
      description: `Caja de Velocidad`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 231,
      custom_value: 120.0,
      max_quantity: 2,
   },
   {
      name: `Pizarra (con o sin relojes)`,
      description: `Pizarra (con o sin relojes)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Defensa (delantera y trasera)`,
      description: `Defensa (delantera y trasera)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Capot`,
      description: `Capot`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Tapa Maletero`,
      description: `Tapa Maletero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Puertas`,
      description: `Puerta`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Bombas de aceite, combustible, agua y cloche`,
      description: `Bomba de aceite, combustible, agua y cloche`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Pistones`,
      description: `Piston`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Camisa piston`,
      description: `Camisa piston`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
      max_quantity: 2,
   },
   {
      name: `Ciguenal`,
      description: `Ciguenal`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Motor de arranque`,
      description: `Motor de arranque`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Radiador`,
      description: `Radiador`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Sistema limpia parabrisas`,
      description: `Sistema limpia parabrisa`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Encendido electrico`,
      description: `Encendido electrico`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Sistemas de clima para autos`,
      description: `Sistema de clima para auto`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 103,
      custom_value: 70.0,
      max_quantity: 2,
   },
   {
      name: `Kit o set de frenos (mangueras, pastillas, discos)`,
      description: `Kit o set de freno (mangueras, pastillas, discos)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Barra estabilizadora`,
      description: `Barra estabilizadora`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Puente delantero`,
      description: `Puente delantero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Radio reproductora para auto`,
      description: `Radio reproductora para auto`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Los demas accesorios, partes, piezas de autos, motos y ciclomotores`,
      description: `Lo demas accesorios, partes, pieza de autos, moto y ciclomotor`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Butacas delantera`,
      description: `Butaca delantera`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Asiento trasero`,
      description: `Asiento trasero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 129,
      custom_value: 80.0,
      max_quantity: 2,
   },
   {
      name: `Asiento para moto o ciclomotor`,
      description: `Asiento para moto o ciclomotor`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Timon para auto`,
      description: `Timon para auto`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Tubo de escape de autos y motos`,
      description: `Tubo de escape de auto y moto`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Cristal de puerta o ventanilla`,
      description: `Cristal de puerta o ventanilla`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
      max_quantity: 2,
   },
   {
      name: `Rodamientos`,
      description: `Rodamiento`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Valvulas de motor`,
      description: `Valvula de motor`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
      max_quantity: 2,
   },
   {
      name: `Diferencial de vehiculos ligeros`,
      description: `Diferencial de vehiculo ligero`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 231,
      custom_value: 120.0,
      max_quantity: 2,
   },
   {
      name: `Diferencial de vehiculos pesados`,
      description: `Diferencial de vehiculo pesado`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 1209,
      custom_value: 500.0,
      max_quantity: 2,
   },
   {
      name: `Camara de vigilancia para auto`,
      description: `Camara de vigilancia para auto`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 309,
      custom_value: 150.0,
      max_quantity: 2,
   },
   {
      name: `Remolque o arrastre ligero sin propulsion`,
      description: `Remolque o arrastre ligero sin propulsion`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 694,
      custom_value: 300.0,
      max_quantity: 2,
   },
   {
      name: `Motores marinos que no excedan los 10 caballos de fuerza (HP)`,
      description: `Motor marino que no excedan lo 10 caballo de fuerza (HP)`,
      chapter: `Vehiculos, Partes y Piezas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2366,
      custom_value: 950.0,
      max_quantity: 2,
   },
   {
      name: `Bicicletas`,
      description: `Bicicleta`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Bicicletas electricas y de pedaleo asistido`,
      description: `Bicicleta electrica y de pedaleo asistido`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 180,
      custom_value: 100.0,
      max_quantity: 2,
   },
   {
      name: `Patinetas y carriolas electricas`,
      description: `Patineta y carriola electrica`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
      max_quantity: 2,
   },
   {
      name: `Bateria para propulsion de bicicletas, patinetas y carriolas electricas`,
      description: `Bateria para propulsion de bicicletas, patineta y carriola electrica`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
      max_quantity: 2,
   },
   {
      name: `Las demas partes, piezas y accesorios de bicicletas, bicicletas electricas, patinetas y carriolas electricas`,
      description: `La demas partes, pieza y accesorio de bicicletas, bicicleta electricas, patineta y carriola electrica`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Balsas y salvavidas`,
      description: `Balsa y salvavida`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Piscinas`,
      description: `Piscina`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 437,
      custom_value: 200.0,
      max_quantity: 2,
   },
   {
      name: `Juegos inflables para uso domestico`,
      description: `Juego inflabl para uso domestico`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2366,
      custom_value: 950.0,
      max_quantity: 2,
   },
   {
      name: `Juguetes inflables para ninos`,
      description: `Juguet inflabl para nino`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
      max_quantity: 2,
   },
   {
      name: `Juguetes de propulsion electrica o no, para ser montados por ninos`,
      description: `Juguet de propulsion electrica o no, para ser montado por nino`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
      max_quantity: 2,
   },
   {
      name: `Juguetes que funcionen con baterias, por control remoto, mecanicos y similares`,
      description: `Juguet que funcionen con baterias, por control remoto, mecanico y similar`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Los demas juguetes`,
      description: `Lo demas juguet`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Articulos para la practica de deportes con pelota (bate, ned, raqueta, careta, cascos, petos, guantes, guantillas)`,
      description: `Articulo para la practica de deport con pelota (bate, ned, raqueta, careta, cascos, petos, guantes, guantillas)`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
      max_quantity: 2,
   },
   {
      name: `Articulos para la practica de deportes nauticos (snocker, aletas, caretas, tablas de surf)`,
      description: `Articulo para la practica de deport nautico (snocker, aletas, caretas, tabla de surf)`,
      chapter: `Juguetes y Articulos de Recreo`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
      max_quantity: 2,
   },
   {
      name: `Los demas articulos para la practica de deportes`,
      description: `Lo demas articulo para la practica de deport`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
   },
   {
      name: `Hilo de pescar`,
      description: `Hilo de pescar`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
   },
   {
      name: `Equipo integrado multifuncional para ejercicio muscular (Hercules)`,
      description: `Equipo integrado multifuncional para ejercicio muscular (Hercules)`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 1466,
      custom_value: 600.0,
   },
   {
      name: `Caminadoras`,
      description: `Caminadora`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
   },
   {
      name: `Escaladora`,
      description: `Escaladora`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
   },
   {
      name: `Bicicleta estatica`,
      description: `Bicicleta estatica`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 951,
      custom_value: 400.0,
   },
   {
      name: `Aeronaves no tripuladas`,
      description: `Aeronav no tripulada`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2366,
      custom_value: 950.0,
   },
   {
      name: `Componentes, partes y piezas de aeronaves no tripuladas`,
      description: `Componentes, part y pieza de aeronav no tripulada`,
      chapter: `nan`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
   },
   {
      name: `Baldosas, azulejos`,
      description: `Baldosas, azulejo`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 6.0,
   },
   {
      name: `Matajuntas`,
      description: `Matajunta`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Cenefas`,
      description: `Cenefa`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Manufacturas p/uso de construccion`,
      description: `Manufactura p/uso de construccion`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 6.0,
   },
   {
      name: `Bolsa de hasta 49 Kg de cementos gris / blanco y otros cementos`,
      description: `Bolsa de hasta 49 Kg de cemento gri / blanco y otro cemento`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 6.0,
   },
   {
      name: `Otros herrajes de cualquier tipo`,
      description: `Otro herraj de cualquier tipo`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 3.0,
   },
   {
      name: `Los demas materiales de construccion`,
      description: `Lo demas material de construccion`,
      chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construccion se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demas materiales de la construccion la cifra a admitir es de 
hasta 10 unidades`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Juego herramientas de mano`,
      description: `Juego herramienta de mano`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 288,
      custom_value: 150.0,
   },
   {
      name: `Herramientas de mano (alicates, cepillos metalicos, cutters, destornilladores, limas y escofinas, llaves ajustables, llaves allen, llaves fijas, llaves de tubo, de vaso, martillos y masas, tenazas, puntas y porta puntas, tijeras, tornillos de banco)`,
      description: `Herramienta de mano (alicates, cepillo metalicos, cutters, destornilladores, lima y escofinas, llav ajustables, llav allen, llav fijas, llav de tubo, de vaso, martillo y masas, tenazas, punta y porta puntas, tijeras, tornillo de banco)`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Útiles intercambiables paramaquinas herramientas electricas`,
      description: `Útil intercambiabl paramaquina herramienta electrica`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Herramientas con motor incorporado (afiladoras, atornilladores electricos y neumaticos, cepillos, clavadoras, decapadoras, grapadoras, lijadoras, martillos, remachadoras, roscadoras, sierras, circulares, taladros y pulidoras, compresores neumaticos pequenos, motosierras)`,
      description: `Herramienta con motor incorporado (afiladoras, atornillador electrico y neumaticos, cepillos, clavadoras, decapadoras, grapadoras, lijadoras, martillos, remachadoras, roscadoras, sierras, circulares, taladro y pulidoras, compresor neumatico pequenos, motosierras)`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
   },
   {
      name: `Plantas de soldar de pequeno formato`,
      description: `Planta de soldar de pequeno formato`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 120,
      custom_value: 80.0,
   },
   {
      name: `Cortadora de cesped portatiles`,
      description: `Cortadora de cesped portatil`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Mochila fumigadora sin motor de combustion`,
      description: `Mochila fumigadora sin motor de combustion`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 70.0,
   },
   {
      name: `Aparatos de medicion y precision (cintas metricas, niveles, multimetros, voltimetros y similares)`,
      description: `Aparato de medicion y precision (cinta metricas, niveles, multimetros, voltimetro y similares)`,
      chapter: `Herramientas`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
   },
   {
      name: `Pinturas, barnices, pigmentos y diluentes`,
      description: `Pinturas, barnices, pigmento y diluent`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 4.0,
   },
   {
      name: `Cables de electricidad`,
      description: `Cabl de electricidad`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Lamparas electricas de senalizacion y alumbrado`,
      description: `Lampara electrica de senalizacion y alumbrado`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
   },
   {
      name: `Linternas`,
      description: `Linterna`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 3.0,
   },
   {
      name: `Tanques de agua`,
      description: `Tanque de agua`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
   },
   {
      name: `Mangueras`,
      description: `Manguera`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 5.0,
   },
   {
      name: `Escaleras domesticas`,
      description: `Escalera domestica`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 30.0,
   },
   {
      name: `Alarmas contra intrusos`,
      description: `Alarma contra intruso`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
   },
   {
      name: `Sistema de video vigilancia`,
      description: `Sistema de video vigilancia`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 888,
      custom_value: 400.0,
   },
   {
      name: `Puertas`,
      description: `Puerta`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Ventanas`,
      description: `Ventana`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
   },
   {
      name: `Taza de bano`,
      description: `Taza de bano`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 55.0,
   },
   {
      name: `Lavamanos con o sin pedestal`,
      description: `Lavamano con o sin pedestal`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
   },
   {
      name: `Banaderas`,
      description: `Banadera`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 408,
      custom_value: 200.0,
   },
   {
      name: `Jacuzzi`,
      description: `Jacuzzi`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 2208,
      custom_value: 950.0,
   },
   {
      name: `Llaves mezcladoras para fregaderos o duchas`,
      description: `Llav mezcladora para fregadero o ducha`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 20.0,
   },
   {
      name: `Revestimientos para el suelo, techos`,
      description: `Revestimiento para el suelo, techo`,
      chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
   },
   {
      name: `Alfombras y similares`,
      description: `Alfombra y similar`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 10.0,
   },
   {
      name: `Tiendas de campana y toldos`,
      description: `Tienda de campana y toldo`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Balon para gas`,
      description: `Balon para ga`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
   },
   {
      name: `Filtros de agua.`,
      description: `Filtro de agua.`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 40.0,
   },
   {
      name: `Juego de neveras plasticas portatiles`,
      description: `Juego de nevera plastica portatil`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 120,
      custom_value: 80.0,
   },
   {
      name: `Neveras plasticas portatiles`,
      description: `Nevera plastica portatil`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 50.0,
   },
   {
      name: `Marqueteria, cofres, cajas, estuches de joyeria y similares`,
      description: `Marqueteria, cofres, cajas, estuch de joyeria y similar`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 8.0,
   },
   {
      name: `Implementos no electricos para coccion de alimentos (Calderos, ollas, cazuelas, sartenes)`,
      description: `Implemento no electrico para coccion de alimento (Calderos, ollas, cazuelas, sartenes)`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
   },
   {
      name: `Caja de seguridad`,
      description: `Caja de seguridad`,
      chapter: `y paredes (linoleos y similares)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 528,
      custom_value: 250.0,
   },
   {
      name: `Camaras fotograficas`,
      description: `Camara fotografica`,
      chapter: `Productos Fotograficos y Cinematograficos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 60.0,
   },
   {
      name: `Camaras de video`,
      description: `Camara de video`,
      chapter: `Productos Fotograficos y Cinematograficos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Proyectores (Data show) y similares`,
      description: `Proyector (Data show) y similar`,
      chapter: `Productos Fotograficos y Cinematograficos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Partes, piezas y accesorios`,
      description: `Partes, pieza y accesorio`,
      chapter: `Productos Fotograficos y Cinematograficos`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 168,
      custom_value: 100.0,
   },
   {
      name: `Papel fotografico`,
      description: `Papel fotografico`,
      chapter: `de productos fotograficos y cinematograficos (tripodes, lentes, fotometros, ampliadora, equipos de iluminacion)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 3.0,
   },
   {
      name: `Papel para impresos`,
      description: `Papel para impreso`,
      chapter: `de productos fotograficos y cinematograficos (tripodes, lentes, fotometros, ampliadora, equipos de iluminacion)`,
      country_id: 1,
      fee_type: FeeType.UNIT,
      fee_in_cents: 100,
      custom_value: 15.0,
   },
];

export const provincesWithCities = [
   {
      id: 1,
      code: "21",
      name: "Pinar del Rio",
      cities: [
         { code: "01", name: "Sandino", city_type: CityType.CITY },
         { code: "02", name: "Mantua", city_type: CityType.CITY },
         { code: "03", name: "Minas de Matahambre", city_type: CityType.CITY },
         { code: "04", name: "Vinales", city_type: CityType.CITY },
         { code: "05", name: "La Palma", city_type: CityType.CITY },
         { code: "06", name: "Los Palacios", city_type: CityType.CITY },
         { code: "07", name: "Consolacion del Sur", city_type: CityType.CITY },
         { code: "08", name: "Pinar del Rio", city_type: CityType.CAPITAL },
         { code: "09", name: "San Luis", city_type: CityType.CITY },
         { code: "10", name: "San Juan y Martinez", city_type: CityType.CITY },
         { code: "11", name: "Guane", city_type: CityType.CITY },
      ],
   },
   {
      id: 2,
      code: "22",
      name: "Artemisa",
      cities: [
         { code: "01", name: "Bahia Honda", city_type: CityType.CITY },
         { code: "02", name: "Mariel", city_type: CityType.CITY },
         { code: "03", name: "Guanajay", city_type: CityType.CITY },
         { code: "04", name: "Caimito", city_type: CityType.CITY },
         { code: "05", name: "Bauta", city_type: CityType.CITY },
         { code: "06", name: "San Antonio de los Banos", city_type: CityType.CITY },
         { code: "07", name: "Guira de Melena", city_type: CityType.CITY },
         { code: "08", name: "Alquizar", city_type: CityType.CITY },
         { code: "09", name: "Artemisa", city_type: CityType.CAPITAL },
         { code: "10", name: "Candelaria", city_type: CityType.CITY },
         { code: "11", name: "San Cristobal", city_type: CityType.CITY },
      ],
   },
   {
      id: 3,
      code: "23",
      name: "La Habana",
      cities: [
         { code: "01", name: "Playa", city_type: CityType.SPECIAL },
         { code: "02", name: "Plaza de la Revolucion", city_type: CityType.SPECIAL },
         { code: "03", name: "Centro Habana", city_type: CityType.SPECIAL },
         { code: "04", name: "Habana Vieja", city_type: CityType.SPECIAL },
         { code: "05", name: "Regla", city_type: CityType.SPECIAL },
         { code: "06", name: "Habana del Este", city_type: CityType.SPECIAL },
         { code: "07", name: "Guanabacoa", city_type: CityType.SPECIAL },
         { code: "08", name: "San Miguel del Padron", city_type: CityType.SPECIAL },
         { code: "09", name: "Diez de Octubre", city_type: CityType.SPECIAL },
         { code: "10", name: "Cerro", city_type: CityType.SPECIAL },
         { code: "11", name: "Marianao", city_type: CityType.SPECIAL },
         { code: "12", name: "La Lisa", city_type: CityType.SPECIAL },
         { code: "13", name: "Boyeros", city_type: CityType.SPECIAL },
         { code: "14", name: "Arroyo Naranjo", city_type: CityType.SPECIAL },
         { code: "15", name: "Cotorro", city_type: CityType.SPECIAL },
      ],
   },
   {
      id: 4,
      code: "24",
      name: "Mayabeque",
      cities: [
         { code: "01", name: "Bejucal", city_type: CityType.CITY },
         { code: "02", name: "San Jose de las Lajas", city_type: CityType.CAPITAL },
         { code: "03", name: "Jaruco", city_type: CityType.CITY },
         { code: "04", name: "Santa Cruz del Norte", city_type: CityType.CITY },
         { code: "05", name: "Madruga", city_type: CityType.CITY },
         { code: "06", name: "Nueva Paz", city_type: CityType.CITY },
         { code: "07", name: "San Nicolas", city_type: CityType.CITY },
         { code: "08", name: "Guines", city_type: CityType.CITY },
         { code: "09", name: "Melena del Sur", city_type: CityType.CITY },
         { code: "10", name: "Batabano", city_type: CityType.CITY },
         { code: "11", name: "Quivican", city_type: CityType.CITY },
      ],
   },
   {
      id: 5,
      code: "25",
      name: "Matanzas",
      cities: [
         { code: "01", name: "Matanzas", city_type: CityType.CAPITAL },
         { code: "02", name: "Cardenas", city_type: CityType.CITY },
         { code: "03", name: "Marti", city_type: CityType.CITY },
         { code: "04", name: "Colon", city_type: CityType.CITY },
         { code: "05", name: "Perico", city_type: CityType.CITY },
         { code: "06", name: "Jovellanos", city_type: CityType.CITY },
         { code: "07", name: "Pedro Betancourt", city_type: CityType.CITY },
         { code: "08", name: "Limonar", city_type: CityType.CITY },
         { code: "09", name: "Union de Reyes", city_type: CityType.CITY },
         { code: "10", name: "Cienaga de Zapata", city_type: CityType.CITY },
         { code: "11", name: "Jaguey Grande", city_type: CityType.CITY },
         { code: "12", name: "Calimete", city_type: CityType.CITY },
         { code: "13", name: "Los Arabos", city_type: CityType.CITY },
      ],
   },
   {
      id: 6,
      code: "26",
      name: "Villa Clara",
      cities: [
         { code: "01", name: "Corralillo", city_type: CityType.CITY },
         { code: "02", name: "Quemado de Guines", city_type: CityType.CITY },
         { code: "03", name: "Sagua la Grande", city_type: CityType.CITY },
         { code: "04", name: "Encrucijada", city_type: CityType.CITY },
         { code: "05", name: "Camajuani", city_type: CityType.CITY },
         { code: "06", name: "Caibarien", city_type: CityType.CITY },
         { code: "07", name: "Remedios", city_type: CityType.CITY },
         { code: "08", name: "Placetas", city_type: CityType.CITY },
         { code: "09", name: "Santa Clara", city_type: CityType.CAPITAL },
         { code: "10", name: "Cifuentes", city_type: CityType.CITY },
         { code: "11", name: "Santo Domingo", city_type: CityType.CITY },
         { code: "12", name: "Ranchuelo", city_type: CityType.CITY },
         { code: "13", name: "Manicaragua", city_type: CityType.CITY },
      ],
   },
   {
      id: 7,
      code: "27",
      name: "Cienfuegos",
      cities: [
         { code: "01", name: "Aguada de Pasajeros", city_type: CityType.CITY },
         { code: "02", name: "Rodas", city_type: CityType.CITY },
         { code: "03", name: "Palmira", city_type: CityType.CITY },
         { code: "04", name: "Lajas", city_type: CityType.CITY },
         { code: "05", name: "Cruces", city_type: CityType.CITY },
         { code: "06", name: "Cumanayagua", city_type: CityType.CITY },
         { code: "07", name: "Cienfuegos", city_type: CityType.CAPITAL },
         { code: "08", name: "Abreus", city_type: CityType.CITY },
      ],
   },
   {
      id: 8,
      code: "28",
      name: "Sancti Spiritus",
      cities: [
         { code: "01", name: "Yaguajay", city_type: CityType.CITY },
         { code: "02", name: "Jatibonico", city_type: CityType.CITY },
         { code: "03", name: "Taguasco", city_type: CityType.CITY },
         { code: "04", name: "Cabaiguan", city_type: CityType.CITY },
         { code: "05", name: "Fomento", city_type: CityType.CITY },
         { code: "06", name: "Trinidad", city_type: CityType.CITY },
         { code: "07", name: "Sancti Spiritus", city_type: CityType.CAPITAL },
         { code: "08", name: "La Sierpe", city_type: CityType.CITY },
      ],
   },
   {
      id: 9,
      code: "29",
      name: "Ciego de Avila",
      cities: [
         { code: "01", name: "Chambas", city_type: CityType.CITY },
         { code: "02", name: "Moron", city_type: CityType.CITY },
         { code: "03", name: "Bolivia", city_type: CityType.CITY },
         { code: "04", name: "Primero de Enero", city_type: CityType.CITY },
         { code: "05", name: "Ciro Redondo", city_type: CityType.CITY },
         { code: "06", name: "Florencia", city_type: CityType.CITY },
         { code: "07", name: "Majagua", city_type: CityType.CITY },
         { code: "08", name: "Ciego de Avila", city_type: CityType.CAPITAL },
         { code: "09", name: "Venezuela", city_type: CityType.CITY },
         { code: "10", name: "Baragua", city_type: CityType.CITY },
      ],
   },
   {
      id: 10,
      code: "30",
      name: "Camaguey",
      cities: [
         { code: "01", name: "Carlos Manuel de Cespedes", city_type: CityType.CITY },
         { code: "02", name: "Esmeralda", city_type: CityType.CITY },
         { code: "03", name: "Sierra de Cubitas", city_type: CityType.CITY },
         { code: "04", name: "Minas", city_type: CityType.CITY },
         { code: "05", name: "Nuevitas", city_type: CityType.CITY },
         { code: "06", name: "Guaimaro", city_type: CityType.CITY },
         { code: "07", name: "Sibanicu", city_type: CityType.CITY },
         { code: "08", name: "Camaguey", city_type: CityType.CAPITAL },
         { code: "09", name: "Florida", city_type: CityType.CITY },
         { code: "10", name: "Vertientes", city_type: CityType.CITY },
         { code: "11", name: "Jimaguayu", city_type: CityType.CITY },
         { code: "12", name: "Najasa", city_type: CityType.CITY },
         { code: "13", name: "Santa Cruz del Sur", city_type: CityType.CITY },
      ],
   },
   {
      id: 11,
      code: "31",
      name: "Las Tunas",
      cities: [
         { code: "01", name: "Manati", city_type: CityType.CITY },
         { code: "02", name: "Puerto Padre", city_type: CityType.CITY },
         { code: "03", name: "Jesus Menendez", city_type: CityType.CITY },
         { code: "04", name: "Majibacoa", city_type: CityType.CITY },
         { code: "05", name: "Las Tunas", city_type: CityType.CAPITAL },
         { code: "06", name: "Jobabo", city_type: CityType.CITY },
         { code: "07", name: "Colombia", city_type: CityType.CITY },
         { code: "08", name: "Amancio", city_type: CityType.CITY },
      ],
   },
   {
      id: 12,
      code: "32",
      name: "Holguin",
      cities: [
         { code: "01", name: "Gibara", city_type: CityType.CITY },
         { code: "02", name: "Rafael Freyre", city_type: CityType.CITY },
         { code: "03", name: "Banes", city_type: CityType.CITY },
         { code: "04", name: "Antilla", city_type: CityType.CITY },
         { code: "05", name: "Baguanos", city_type: CityType.CITY },
         { code: "06", name: "Holguin", city_type: CityType.CAPITAL },
         { code: "07", name: "Calixto Garcia", city_type: CityType.CITY },
         { code: "08", name: "Cacocum", city_type: CityType.CITY },
         { code: "09", name: "Urbano Noris", city_type: CityType.CITY },
         { code: "10", name: "Cueto", city_type: CityType.CITY },
         { code: "11", name: "Mayari", city_type: CityType.CITY },
         { code: "12", name: "Frank Pais", city_type: CityType.CITY },
         { code: "13", name: "Sagua de Tanamo", city_type: CityType.CITY },
         { code: "14", name: "Moa", city_type: CityType.CITY },
      ],
   },
   {
      id: 13,
      code: "33",
      name: "Granma",
      cities: [
         { code: "01", name: "Rio Cauto", city_type: CityType.CITY },
         { code: "02", name: "Cauto Cristo", city_type: CityType.CITY },
         { code: "03", name: "Jiguani", city_type: CityType.CITY },
         { code: "04", name: "Bayamo", city_type: CityType.CAPITAL },
         { code: "05", name: "Yara", city_type: CityType.CITY },
         { code: "06", name: "Manzanillo", city_type: CityType.CITY },
         { code: "07", name: "Campechuela", city_type: CityType.CITY },
         { code: "08", name: "Media Luna", city_type: CityType.CITY },
         { code: "09", name: "Niquero", city_type: CityType.CITY },
         { code: "10", name: "Pilon", city_type: CityType.CITY },
         { code: "11", name: "Bartolome Maso", city_type: CityType.CITY },
         { code: "12", name: "Buey Arriba", city_type: CityType.CITY },
         { code: "13", name: "Guisa", city_type: CityType.CITY },
      ],
   },
   {
      id: 14,
      code: "34",
      name: "Santiago de Cuba",
      cities: [
         { code: "01", name: "Contramaestre", city_type: CityType.CITY },
         { code: "02", name: "Mella", city_type: CityType.CITY },
         { code: "03", name: "San Luis", city_type: CityType.CITY },
         { code: "04", name: "Segundo Frente", city_type: CityType.CITY },
         { code: "05", name: "Songo La Maya", city_type: CityType.CITY },
         { code: "06", name: "Santiago de Cuba", city_type: CityType.CAPITAL },
         { code: "07", name: "Palma Soriano", city_type: CityType.CITY },
         { code: "08", name: "Tercer Frente", city_type: CityType.CITY },
         { code: "09", name: "Guama", city_type: CityType.CITY },
      ],
   },
   {
      id: 15,
      code: "35",
      name: "Guantanamo",
      cities: [
         { code: "01", name: "El Salvador", city_type: CityType.CITY },
         { code: "02", name: "Manuel Tames", city_type: CityType.CITY },
         { code: "03", name: "Yateras", city_type: CityType.CITY },
         { code: "04", name: "Baracoa", city_type: CityType.CITY },
         { code: "05", name: "Maisi", city_type: CityType.CITY },
         { code: "06", name: "Imias", city_type: CityType.CITY },
         { code: "07", name: "San Antonio del Sur", city_type: CityType.CITY },
         { code: "08", name: "Caimanera", city_type: CityType.CITY },
         { code: "09", name: "Guantanamo", city_type: CityType.CAPITAL },
         { code: "10", name: "Niceto Perez", city_type: CityType.CITY },
      ],
   },
   {
      id: 16,
      code: "40",
      name: "Isla de la Juventud",
      cities: [{ code: "01", name: "Isla de la Juventud", city_type: CityType.CAPITAL }],
   },
];
