import { PrismaClient, FeeType } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
	const rows = [
		{
			name: `Planchas eléctricas domésticas`,
			description: `Plancha eléctrica doméstica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Refrigeradores domésticos`,
			description: `Refrigerador doméstico`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 694,
			custom_value: 300.0,
		},
		{
			name: `Congeladores o freezer domésticos.`,
			description: `Congelador o freezer domésticos.`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 823,
			custom_value: 350.0,
		},
		{
			name: `Dispensadores de agua`,
			description: `Dispensador de agua`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Minibar.`,
			description: `Minibar.`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Cocina y hornos de gas`,
			description: `Cocina y horno de ga`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Cocina y hornillas eléctricas por inducción`,
			description: `Cocina y hornilla eléctrica por inducción`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Cocinas y hornillas eléctricas sin horno`,
			description: `Cocina y hornilla eléctrica sin horno`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Cocinas y hornillas eléctricas sin horno`,
			description: `Cocina y hornilla eléctrica sin horno`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2109,
			custom_value: 850.0,
		},
		{
			name: `Extractor de grasa y campana`,
			description: `Extractor de grasa y campana`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Horno microonda`,
			description: `Horno microonda`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Hornos eléctricos para uso doméstico`,
			description: `Horno eléctrico para uso doméstico`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Parrillada o grill`,
			description: `Parrillada o grill`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Sartenes eléctricos y similares`,
			description: `Sarten eléctrico y similar`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Olla arrocera eléctrica`,
			description: `Olla arrocera eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Olla vaporera eléctrica`,
			description: `Olla vaporera eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Olla multifunción eléctrica`,
			description: `Olla multifunción eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Olla asadora de convección halógena`,
			description: `Olla asadora de convección halógena`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Freidora eléctrica`,
			description: `Freidora eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Sandwichera eléctrica`,
			description: `Sandwichera eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Tostadora eléctrica de pan`,
			description: `Tostadora eléctrica de pan`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Máquinas lavadoras/ secadoras domésticas`,
			description: `Máquina lavadoras/ secadora doméstica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Lava vajilla doméstico`,
			description: `Lava vajilla doméstico`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Máquina de coser, tejer y bordar`,
			description: `Máquina de coser, tejer y bordar`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Secador o rizador / plancha de pelo`,
			description: `Secador o rizador / plancha de pelo`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Secador de cabellos`,
			description: `Secador de cabellos`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Máquina de pelar eléctrica`,
			description: `Máquina de pelar eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Aspiradora`,
			description: `Aspiradora`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Ducha eléctrica`,
			description: `Ducha eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Calentador de agua Electrico`,
			description: `Calentador de agua Electrico`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 103,
			custom_value: 70.0,
		},
		{
			name: `– Calentador de Agua Gas`,
			description: `– Calentador de Agua Ga`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Cafetera eléctrica`,
			description: `Cafetera eléctrica`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Batidora`,
			description: `Batidora`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Licuadora`,
			description: `Licuadora`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Procesador de alimentos`,
			description: `Procesador de alimento`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Picador de especies y vegetales`,
			description: `Picador de especie y vegetal`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Mezcladoras`,
			description: `Mezcladora`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Molinos`,
			description: `Molino`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Televisores convencionales`,
			description: `Televisor convencional`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `-Televisores pantalla plana hasta 32 pulgadas`,
			description: `-Televisor pantalla plana hasta 32 pulgada`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 566,
			custom_value: 250.0,
		},
		{
			name: `-Televisores pantalla plana mayores de 32 pulgadas hasta 42 pulgadas`,
			description: `-Televisor pantalla plana mayor de 32 pulgada hasta 42 pulgada`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `-Televisores pantalla plana mayores de 42 pulgadas`,
			description: `-Televisor pantalla plana mayor de 42 pulgada`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 1209,
			custom_value: 500.0,
		},
		{
			name: `Caja decodificadora digital TV`,
			description: `Caja decodificadora digital TV`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Equipos de música`,
			description: `Equipo de música`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Equipo de música portátil`,
			description: `Equipo de música portátil`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Teatro en casa o similares`,
			description: `Teatro en casa o similar`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 231,
			custom_value: 120.0,
		},
		{
			name: `Mezclador de sonido`,
			description: `Mezclador de sonido`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `Reproductor de vídeo`,
			description: `Reproductor de vídeo`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 200,
			custom_value: 20.0,
		},
		{
			name: `Consolas de vídeo juegos`,
			description: `Consola de vídeo juego`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Ventiladores`,
			description: `Ventilador`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Aire Acondicionado/Split (hasta 9000 BTU)`,
			description: `Aire Acondicionado/Split (hasta 9000 BTU)`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Aire Acondicionado/Split (mayor de 9000 hasta 12000 BTU)`,
			description: `Aire Acondicionado/Split (mayor de 9000 hasta 12000 BTU)`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Aire Acondicionado/Split (mayor de 12000 BTU hasta 24000 BTU)`,
			description: `Aire Acondicionado/Split (mayor de 12000 BTU hasta 24000 BTU)`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 1851,
			custom_value: 750.0,
		},
		{
			name: `Generadores Electricos hasta 900 va`,
			description: `Generador Electrico hasta 900 va`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Generadores Electricos Mayores de 900 va hasta 1500 va`,
			description: `Generador Electrico de 900 va hasta 1500 va`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 1209,
			custom_value: 500.0,
		},
		{
			name: `Generadores Electricos Mayores de 1500 va hasta 15 Kva`,
			description: `Generador Electrico de 1500 va hasta 15 Kva`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2366,
			custom_value: 950.0,
		},
		{
			name: `Casco o armazón de refrigeradores, freezer y aires acondicionados con todos los componentes excepto el compresor`,
			description: `Casco o armazón de refrigeradores, freezer y air acondicionado con todo lo component excepto el compresor`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 566,
			custom_value: 250.0,
		},
		{
			name: `Otros tipos de motores de equipos electrodomésticos`,
			description: `Otro tipo de motor de equipo electrodoméstico`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Compresores de equipos de clima y refrigeración`,
			description: `Compresor de equipo de clima y refrigeración`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Bombas de agua o compresores para agua`,
			description: `Bomba de agua o compresor para agua`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Partes, piezas y accesorios de compresores y bombas para agua`,
			description: `Partes, pieza y accesorio de compresor y bomba para agua`,
			chapter: `Electrodomesticos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Microcomputadora completa de Mesa Mesa`,
			description: `Microcomputadora completa de Mesa Mesa`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Microcomputadora portátil (laptop).`,
			description: `Microcomputadora portátil (laptop).`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 566,
			custom_value: 250.0,
		},
		{
			name: `Table PC, dispositivos para la lectura digital y productos similares`,
			description: `– Table PC, dispositivo para la lectura digital y producto similar`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Mini laptop`,
			description: `– Mini laptop`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Dispositivos de almacenamiento, memorias y similares`,
			description: `Dispositivo de almacenamiento, memoria y similar`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Torre de computadora`,
			description: `Torre de computadora`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 103,
			custom_value: 70.0,
		},
		{
			name: `Disco duro incluyendo el HDD player`,
			description: `Disco duro incluyendo el HDD player.`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Monitor de computadora`,
			description: `Monitor de computadora`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Backup (UPS)`,
			description: `Backup (UPS)`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Impresoras. Fotocopiadoras`,
			description: `Impresoras. Fotocopiadora`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Scanners`,
			description: `Scanner`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Teléfonos convencionales alámbricos`,
			description: `Teléfono convencional alámbrico`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Teléfonos inalámbricos`,
			description: `Teléfono inalámbrico`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Teléfonos celulares o inteligentes`,
			description: `Teléfono celular o inteligent`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Intercomunicadores domésticos`,
			description: `Intercomunicador doméstico`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Fax alámbrico`,
			description: `Fax alámbrico`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Equipos de fax inalámbricos`,
			description: `Equipo de fax inalámbrico`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Micrófonos inalámbricos y sus accesorios`,
			description: `Micrófono inalámbrico y su accesorio`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Micrófonos alámbricos y sus accesorios`,
			description: `Micrófono alámbrico y su accesorio`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Dispositivos para redes de datos (routers, switches y similares).`,
			description: `Dispositivo para red de dato (routers, switch y similares).`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Transmisores y transceptores de radio de cualquier naturaleza y servicios, estaciones fijas, móviles y personales (walkie-talkie y teléfonos satelitales), sus dispositivos y amplificadores de potencia`,
			description: `Transmisor y transceptor de radio de cualquier naturaleza y servicios, estacion fijas, móvil y personal (walkie-talkie y teléfono satelitales), su dispositivo y amplificador de potencia`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Geolocalizador`,
			description: `Geolocalizador`,
			chapter: `Equipos de Computo o Similares`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Instrumentos de cuerda`,
			description: `Instrumento de cuerda`,
			chapter: `Instrumentos Musicales`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Instrumentos de teclado`,
			description: `Instrumento de teclado`,
			chapter: `Instrumentos Musicales`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Instrumentos de viento`,
			description: `Instrumento de viento`,
			chapter: `Instrumentos Musicales`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Instrumentos de percusión`,
			description: `Instrumento de percusión`,
			chapter: `Instrumentos Musicales`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Los demás instrumentos musicales`,
			description: `Lo demás instrumento musical`,
			chapter: `Instrumentos Musicales`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 694,
			custom_value: 300.0,
		},
		{
			name: `Juego de sala`,
			description: `Juego de sala`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Juego de cuarto`,
			description: `Juego de cuarto`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Juego de comedor`,
			description: `Juego de comedor`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 231,
			custom_value: 120.0,
		},
		{
			name: `Juego de mueble de cocinas compuesta por módulos sin electrodomésticos incluidos`,
			description: `Juego de mueble de cocina compuesta por módulo sin electrodoméstico incluido`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `Piezas de muebles (silla, mesa, butaca, sillones y similares)`,
			description: `Pieza de muebl (silla, mesa, butaca, sillon y similares)`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Sillas giratorias`,
			description: `Silla giratoria`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Buros.`,
			description: `Buros.`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Mesa para computadoras`,
			description: `Mesa para computadora`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Libreros`,
			description: `Librero`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Estantes`,
			description: `Estant`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 103,
			custom_value: 70.0,
		},
		{
			name: `Cómodas y gaveteros`,
			description: `Cómoda y gavetero`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Repisas`,
			description: `Repisa`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Colchones`,
			description: `Colchon`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Los demás muebles`,
			description: `Lo demás muebl`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Muebles para uso del bebé (cuna, coches, corrales, mecedoras, andadores y similares)`,
			description: `Muebl para uso del bebé (cuna, coches, corrales, mecedoras, andador y similares)`,
			chapter: `Mobiliario`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Ciclomotores eléctricos de hasta dos plazas`,
			description: `Ciclomotor eléctrico de hasta do plaza`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Baterías o acumuladores de litio`,
			description: `Batería o acumulador de litio`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Otras baterías y acumuladores`,
			description: `Otra batería y acumulador`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 35.0,
		},
		{
			name: `Kit o set de baterías de Gel`,
			description: `Kit o set de batería de Gel`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Carburador`,
			description: `Carburador`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Delco (distribuidor)`,
			description: `Delco (distribuidor)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Guardafangos`,
			description: `Guardafango`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Parabrisas`,
			description: `Parabrisa`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Neumáticos para autos ligeros (con o sin cámaras)`,
			description: `Neumático para auto ligero (con o sin cámaras)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Neumáticos para autos pesados (con o sin cámaras)`,
			description: `Neumático para auto pesado (con o sin cámaras)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Neumáticos para motos o ciclomotores (con o sin cámaras)`,
			description: `Neumático para moto o ciclomotor (con o sin cámaras)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 35.0,
		},
		{
			name: `Cámaras para neumáticos de autos ligeros`,
			description: `Cámara para neumático de auto ligero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Cámaras para neumáticos de autos pesados`,
			description: `Cámara para neumático de auto pesado`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Cámaras para neumáticos de motos o ciclomotores`,
			description: `Cámara para neumático de moto o ciclomotor`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Llantas para autos ligeros`,
			description: `Llanta para auto ligero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Llantas para autos pesados`,
			description: `Llanta para auto pesado`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Llantas para motos o ciclomotores`,
			description: `Llanta para moto o ciclomotor`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 35.0,
		},
		{
			name: `Amortiguadores`,
			description: `Amortiguador`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Bobina de encendido`,
			description: `Bobina de encendido`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Cajas de Velocidad`,
			description: `Caja de Velocidad`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 231,
			custom_value: 120.0,
		},
		{
			name: `Pizarra (con o sin relojes)`,
			description: `Pizarra (con o sin relojes)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Defensa (delantera y trasera)`,
			description: `Defensa (delantera y trasera)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Capot`,
			description: `Capot`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Tapa Maletero`,
			description: `Tapa Maletero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Puertas`,
			description: `Puerta`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Bombas de aceite, combustible, agua y cloche`,
			description: `Bomba de aceite, combustible, agua y cloche`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Pistones`,
			description: `Piston`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Camisa pistón`,
			description: `Camisa pistón`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Cigüeñal`,
			description: `Cigüeñal`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Motor de arranque`,
			description: `Motor de arranque`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Radiador`,
			description: `Radiador`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Sistema limpia parabrisas`,
			description: `Sistema limpia parabrisa`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Encendido eléctrico`,
			description: `Encendido eléctrico`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Sistemas de clima para autos`,
			description: `Sistema de clima para auto`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 103,
			custom_value: 70.0,
		},
		{
			name: `Kit o set de frenos (mangueras, pastillas, discos)`,
			description: `Kit o set de freno (mangueras, pastillas, discos)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Barra estabilizadora`,
			description: `Barra estabilizadora`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Puente delantero`,
			description: `Puente delantero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Radio reproductora para auto`,
			description: `Radio reproductora para auto`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Los demás accesorios, partes, piezas de autos, motos y ciclomotores`,
			description: `Lo demás accesorios, partes, pieza de autos, moto y ciclomotor`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Butacas delantera`,
			description: `Butaca delantera`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Asiento trasero`,
			description: `Asiento trasero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 129,
			custom_value: 80.0,
		},
		{
			name: `Asiento para moto o ciclomotor`,
			description: `Asiento para moto o ciclomotor`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Timón para auto`,
			description: `Timón para auto`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Tubo de escape de autos y motos`,
			description: `Tubo de escape de auto y moto`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Cristal de puerta o ventanilla`,
			description: `Cristal de puerta o ventanilla`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Rodamientos`,
			description: `Rodamiento`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Válvulas de motor`,
			description: `Válvula de motor`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Diferencial de vehículos ligeros`,
			description: `Diferencial de vehículo ligero`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 231,
			custom_value: 120.0,
		},
		{
			name: `Diferencial de vehículos pesados`,
			description: `Diferencial de vehículo pesado`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 1209,
			custom_value: 500.0,
		},
		{
			name: `Cámara de vigilancia para auto`,
			description: `Cámara de vigilancia para auto`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 309,
			custom_value: 150.0,
		},
		{
			name: `Remolque o arrastre ligero sin propulsión`,
			description: `Remolque o arrastre ligero sin propulsión`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 694,
			custom_value: 300.0,
		},
		{
			name: `Motores marinos que no excedan los 10 caballos de fuerza (HP)`,
			description: `Motor marino que no excedan lo 10 caballo de fuerza (HP)`,
			chapter: `Vehiculos, Partes y Piezas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2366,
			custom_value: 950.0,
		},
		{
			name: `Bicicletas`,
			description: `Bicicleta`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Bicicletas eléctricas y de pedaleo asistido`,
			description: `Bicicleta eléctrica y de pedaleo asistido`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 180,
			custom_value: 100.0,
		},
		{
			name: `Patinetas y carriolas eléctricas`,
			description: `Patineta y carriola eléctrica`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Batería para propulsión de bicicletas, patinetas y carriolas eléctricas`,
			description: `Batería para propulsión de bicicletas, patineta y carriola eléctrica`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Las demás partes, piezas y accesorios de bicicletas, bicicletas eléctricas, patinetas y carriolas eléctricas`,
			description: `La demás partes, pieza y accesorio de bicicletas, bicicleta eléctricas, patineta y carriola eléctrica`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Balsas y salvavidas`,
			description: `Balsa y salvavida`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Piscinas`,
			description: `Piscina`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 437,
			custom_value: 200.0,
		},
		{
			name: `Juegos inflables para uso doméstico`,
			description: `Juego inflabl para uso doméstico`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2366,
			custom_value: 950.0,
		},
		{
			name: `Juguetes inflables para niños`,
			description: `Juguet inflabl para niño`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Juguetes de propulsión eléctrica o no, para ser montados por niños`,
			description: `Juguet de propulsión eléctrica o no, para ser montado por niño`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Juguetes que funcionen con baterías, por control remoto, mecánicos y similares`,
			description: `Juguet que funcionen con baterías, por control remoto, mecánico y similar`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Los demás juguetes`,
			description: `Lo demás juguet`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Artículos para la práctica de deportes con pelota (bate, ned, raqueta, careta, cascos, petos, guantes, guantillas)`,
			description: `Artículo para la práctica de deport con pelota (bate, ned, raqueta, careta, cascos, petos, guantes, guantillas)`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Artículos para la práctica de deportes náuticos (snocker, aletas, caretas, tablas de surf)`,
			description: `Artículo para la práctica de deport náutico (snocker, aletas, caretas, tabla de surf)`,
			chapter: `Juguetes y Articulos de Recreo`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Los demás artículos para la práctica de deportes`,
			description: `Lo demás artículo para la práctica de deport`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Hilo de pescar`,
			description: `Hilo de pescar`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Equipo integrado multifuncional para ejercicio muscular (Hércules)`,
			description: `Equipo integrado multifuncional para ejercicio muscular (Hércules)`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 1466,
			custom_value: 600.0,
		},
		{
			name: `Caminadoras`,
			description: `Caminadora`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `Escaladora`,
			description: `Escaladora`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `Bicicleta estática`,
			description: `Bicicleta estática`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 951,
			custom_value: 400.0,
		},
		{
			name: `Aeronaves no tripuladas`,
			description: `Aeronav no tripulada`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2366,
			custom_value: 950.0,
		},
		{
			name: `Componentes, partes y piezas de aeronaves no tripuladas`,
			description: `Componentes, part y pieza de aeronav no tripulada`,
			chapter: `nan`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Baldosas, azulejos`,
			description: `Baldosas, azulejo`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 6.0,
		},
		{
			name: `Matajuntas`,
			description: `Matajunta`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Cenefas`,
			description: `Cenefa`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Manufacturas p/uso de construcción`,
			description: `Manufactura p/uso de construcción`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 6.0,
		},
		{
			name: `Bolsa de hasta 49 Kg de cementos gris / blanco y otros cementos`,
			description: `Bolsa de hasta 49 Kg de cemento gri / blanco y otro cemento`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 6.0,
		},
		{
			name: `Otros herrajes de cualquier tipo`,
			description: `Otro herraj de cualquier tipo`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 3.0,
		},
		{
			name: `Los demás materiales de construcción`,
			description: `Lo demás material de construcción`,
			chapter: `Materiales de ConstruccionLos materiales que clasifican como piezas de enchape y piso se admiten hasta 50 m2 
excepto en los matajuntas, cenefas y similares que se admiten en igual cifra pero su uni dad de medida es metro lineal.
Las manufacturas para uso de la construcción se admiten hasta 50 unidades y los otros 
herrajes de cualquier tipo y demás materiales de la construcción la cifra a admitir es de 
hasta 10 unidades`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Juego herramientas de mano`,
			description: `Juego herramienta de mano`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 288,
			custom_value: 150.0,
		},
		{
			name: `Herramientas de mano (alicates, cepillos metálicos, cutters, destornilladores, limas y escofinas, llaves ajustables, llaves allen, llaves fijas, llaves de tubo, de vaso, martillos y masas, tenazas, puntas y porta puntas, tijeras, tornillos de banco)`,
			description: `Herramienta de mano (alicates, cepillo metálicos, cutters, destornilladores, lima y escofinas, llav ajustables, llav allen, llav fijas, llav de tubo, de vaso, martillo y masas, tenazas, punta y porta puntas, tijeras, tornillo de banco)`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Útiles intercambiables paramáquinas herramientas eléctricas`,
			description: `Útil intercambiabl paramáquina herramienta eléctrica`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Herramientas con motor incorporado (afiladoras, atornilladores eléctricos y neumáticos, cepillos, clavadoras, decapadoras, grapadoras, lijadoras, martillos, remachadoras, roscadoras, sierras, circulares, taladros y pulidoras, compresores neumáticos pequeños, motosierras)`,
			description: `Herramienta con motor incorporado (afiladoras, atornillador eléctrico y neumáticos, cepillos, clavadoras, decapadoras, grapadoras, lijadoras, martillos, remachadoras, roscadoras, sierras, circulares, taladro y pulidoras, compresor neumático pequeños, motosierras)`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Plantas de soldar de pequeño formato`,
			description: `Planta de soldar de pequeño formato`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 120,
			custom_value: 80.0,
		},
		{
			name: `Cortadora de césped portátiles`,
			description: `Cortadora de césped portátil`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Mochila fumigadora sin motor de combustión`,
			description: `Mochila fumigadora sin motor de combustión`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 70.0,
		},
		{
			name: `Aparatos de medición y precisión (cintas métricas, niveles, multímetros, voltímetros y similares)`,
			description: `Aparato de medición y precisión (cinta métricas, niveles, multímetros, voltímetro y similares)`,
			chapter: `Herramientas`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Pinturas, barnices, pigmentos y diluentes`,
			description: `Pinturas, barnices, pigmento y diluent`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 4.0,
		},
		{
			name: `Cables de electricidad`,
			description: `Cabl de electricidad`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Lámparas eléctricas de señalización y alumbrado`,
			description: `Lámpara eléctrica de señalización y alumbrado`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Linternas`,
			description: `Linterna`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 3.0,
		},
		{
			name: `Tanques de agua`,
			description: `Tanque de agua`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Mangueras`,
			description: `Manguera`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 5.0,
		},
		{
			name: `Escaleras domésticas`,
			description: `Escalera doméstica`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 30.0,
		},
		{
			name: `Alarmas contra intrusos`,
			description: `Alarma contra intruso`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Sistema de video vigilancia`,
			description: `Sistema de video vigilancia`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 888,
			custom_value: 400.0,
		},
		{
			name: `Puertas`,
			description: `Puerta`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Ventanas`,
			description: `Ventana`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Taza de baño`,
			description: `Taza de baño`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 55.0,
		},
		{
			name: `Lavamanos con o sin pedestal`,
			description: `Lavamano con o sin pedestal`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Bañaderas`,
			description: `Bañadera`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 408,
			custom_value: 200.0,
		},
		{
			name: `Jacuzzi`,
			description: `Jacuzzi`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 2208,
			custom_value: 950.0,
		},
		{
			name: `Llaves mezcladoras para fregaderos o duchas`,
			description: `Llav mezcladora para fregadero o ducha`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 20.0,
		},
		{
			name: `Revestimientos para el suelo, techos`,
			description: `Revestimiento para el suelo, techo`,
			chapter: `Pinturas Barnices y Articulos para el Hogar y de Ferreteria`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Alfombras y similares`,
			description: `Alfombra y similar`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 10.0,
		},
		{
			name: `Tiendas de campaña y toldos`,
			description: `Tienda de campaña y toldo`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Balón para gas`,
			description: `Balón para ga`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Filtros de agua.`,
			description: `Filtro de agua.`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 40.0,
		},
		{
			name: `Juego de neveras plásticas portátiles`,
			description: `Juego de nevera plástica portátil`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 120,
			custom_value: 80.0,
		},
		{
			name: `Neveras plásticas portátiles`,
			description: `Nevera plástica portátil`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 50.0,
		},
		{
			name: `Marquetería, cofres, cajas, estuches de joyería y similares`,
			description: `Marquetería, cofres, cajas, estuch de joyería y similar`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 8.0,
		},
		{
			name: `Implementos no eléctricos para cocción de alimentos (Calderos, ollas, cazuelas, sartenes)`,
			description: `Implemento no eléctrico para cocción de alimento (Calderos, ollas, cazuelas, sartenes)`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
		{
			name: `Caja de seguridad`,
			description: `Caja de seguridad`,
			chapter: `y paredes (linóleos y similares)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 528,
			custom_value: 250.0,
		},
		{
			name: `Cámaras fotográficas`,
			description: `Cámara fotográfica`,
			chapter: `Productos Fotograficos y Cinematograficos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 60.0,
		},
		{
			name: `Cámaras de vídeo`,
			description: `Cámara de vídeo`,
			chapter: `Productos Fotograficos y Cinematograficos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Proyectores (Data show) y similares`,
			description: `Proyector (Data show) y similar`,
			chapter: `Productos Fotograficos y Cinematograficos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Partes, piezas y accesorios`,
			description: `Partes, pieza y accesorio`,
			chapter: `Productos Fotograficos y Cinematograficos`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 168,
			custom_value: 100.0,
		},
		{
			name: `Papel fotográfico`,
			description: `Papel fotográfico`,
			chapter: `de productos fotográficos y cinematográficos (trípodes, lentes, fotómetros, ampliadora, equipos de iluminación)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 3.0,
		},
		{
			name: `Papel para impresos`,
			description: `Papel para impreso`,
			chapter: `de productos fotográficos y cinematográficos (trípodes, lentes, fotómetros, ampliadora, equipos de iluminación)`,
			country_id: 1,
			fee_type: FeeType.UNIT,
			fee_in_cents: 100,
			custom_value: 15.0,
		},
	];

	for (const r of rows) {
		// Update by name if exists, otherwise create
		const res = await prisma.customsRates.updateMany({
			where: { name: r.name },
			data: {
				description: r.description ?? undefined,
				chapter: r.chapter ?? undefined,
				country_id: r.country_id,
				fee_type: r.fee_type,
				fee_in_cents: r.fee_in_cents,
				custom_value: r.custom_value as number | null,
			},
		});
		if (res.count === 0) {
			await prisma.customsRates.create({ data: r });
		}
	}
}

main()
	.then(async () => {
		await prisma.$disconnect();
	})
	.catch(async (e) => {
		console.error(e);
		await prisma.$disconnect();
		process.exit(1);
	});
